import type { SymptomDefinition } from "@/types/symptoms";

/** Legacy urgent warning signs — ids must not change (saved logs reference them). */
const LEGACY_URGENT: SymptomDefinition[] = [
  {
    id: "headache",
    label: "Headache that won't go away or gets worse over time",
    icon: "🧠",
    keywords: ["headache", "migraine", "head pain", "severe headache"],
    urgent: true,
  },
  {
    id: "dizziness",
    label: "Dizziness or fainting",
    icon: "😵‍💫",
    keywords: ["dizzy", "faint", "lightheaded", "vertigo"],
    urgent: true,
  },
  {
    id: "vision",
    label: "Changes in your vision",
    icon: "👁️",
    keywords: ["vision", "blurry", "sight", "eyes", "vision changes"],
    urgent: true,
  },
  {
    id: "fever",
    label: "Fever of 100.4° F or higher",
    icon: "🌡️",
    keywords: ["fever", "temperature", "hot", "38"],
    urgent: true,
  },
  {
    id: "swelling",
    label: "Extreme swelling of your hands or face",
    icon: "🤚",
    keywords: ["swelling", "edema", "puffy", "hands", "face"],
    urgent: true,
  },
  {
    id: "harm-thoughts",
    label: "Thoughts of harming yourself or your baby",
    icon: "💭",
    keywords: ["harm", "self-harm", "suicide", "thoughts", "baby"],
    urgent: true,
  },
  {
    id: "breathing",
    label: "Trouble breathing",
    icon: "🫁",
    keywords: ["breathing", "breathless", "shortness of breath", "dyspnea", "sob"],
    urgent: true,
  },
  {
    id: "chest-pain",
    label: "Chest pain or fast beating heart",
    icon: "💓",
    keywords: ["chest", "heart", "palpitations", "cardiac", "chest pain"],
    urgent: true,
  },
  {
    id: "nausea",
    label: "Severe nausea and throwing up",
    icon: "🤢",
    keywords: ["nausea", "vomit", "sick", "throwing up"],
    urgent: true,
  },
  {
    id: "belly-pain",
    label: "Severe belly pain that doesn't go away",
    icon: "🤰",
    keywords: ["belly", "abdominal", "stomach", "cramping", "severe belly pain"],
    urgent: true,
  },
  {
    id: "baby-movement",
    label: "Baby's movement stopping or slowing during pregnancy",
    icon: "👣",
    keywords: ["baby", "movement", "kick", "fetal", "decreased movement"],
    urgent: true,
  },
  {
    id: "leg-pain",
    label: "Severe swelling, redness or pain of your leg or arm",
    icon: "🦵",
    keywords: ["leg", "arm", "clot", "dvt", "redness", "numbness", "weakness"],
    urgent: true,
  },
  {
    id: "bleeding-pregnancy",
    label: "Vaginal bleeding or fluid leaking during pregnancy",
    icon: "🩸",
    keywords: ["bleeding", "pregnancy", "leaking", "fluid"],
    urgent: true,
  },
  {
    id: "bleeding-postpartum",
    label: "Heavy vaginal bleeding or discharge after pregnancy",
    icon: "🩸",
    keywords: ["bleeding", "postpartum", "discharge", "after birth", "unusual discharge"],
    urgent: true,
  },
  {
    id: "tiredness",
    label: "Overwhelming tiredness",
    icon: "😴",
    keywords: ["tired", "fatigue", "exhausted", "weak", "overwhelming tiredness"],
    urgent: true,
  },
];

const MOOD_TIER_SYMPTOMS: SymptomDefinition[] = [
  // —— Very unpleasant (additional) ——
  {
    id: "chest-pressure-squeezing",
    label: "Chest pressure or squeezing",
    icon: "💓",
    keywords: ["chest pressure", "squeezing", "tight chest"],
    urgent: true,
  },
  {
    id: "racing-heart",
    label: "Racing or pounding heart",
    icon: "💓",
    keywords: ["racing heart", "pounding heart", "palpitations", "tachycardia"],
    urgent: true,
  },
  {
    id: "sudden-shortness-breath",
    label: "Sudden shortness of breath",
    icon: "🫁",
    keywords: ["sudden", "shortness of breath", "sob", "breathless"],
    urgent: true,
  },
  {
    id: "severe-panic",
    label: "Severe panic",
    icon: "😰",
    keywords: ["panic", "panic attack", "anxiety attack"],
    urgent: true,
  },
  {
    id: "detachment-reality",
    label: "Detachment from reality",
    icon: "🌀",
    keywords: ["detachment", "dissociation", "unreality", "derealization"],
    urgent: true,
  },
  {
    id: "dizziness-sudden",
    label: "Sudden dizziness",
    icon: "😵‍💫",
    keywords: ["sudden dizziness", "dizzy", "lightheaded"],
    urgent: true,
  },
  {
    id: "fainting",
    label: "Fainting",
    icon: "😵",
    keywords: ["fainting", "passed out", "syncope", "blackout"],
    urgent: true,
  },
  {
    id: "swelling-extreme-body",
    label: "Extreme swelling of hands, face, legs, or arms",
    icon: "🤚",
    keywords: ["swelling", "edema", "hands", "face", "legs", "arms", "extreme"],
    urgent: true,
  },
  {
    id: "numbness-weakness-sudden",
    label: "Sudden numbness or weakness",
    icon: "🦵",
    keywords: ["numbness", "weakness", "stroke", "sudden"],
    urgent: true,
  },
  // —— Unpleasant ——
  {
    id: "chest-discomfort-mild",
    label: "Mild or intermittent chest discomfort",
    icon: "💓",
    keywords: ["chest discomfort", "mild chest", "intermittent chest"],
    urgent: true,
  },
  {
    id: "sob-light-activity",
    label: "Shortness of breath during light activity",
    icon: "🫁",
    keywords: ["shortness of breath", "activity", "exertion", "sob"],
    urgent: true,
  },
  {
    id: "swelling-ankles-feet",
    label: "Swelling in ankles or feet",
    icon: "🦶",
    keywords: ["ankles", "feet", "swelling", "edema"],
    urgent: true,
  },
  {
    id: "dizziness-standing",
    label: "Persistent dizziness when standing up",
    icon: "😵‍💫",
    keywords: ["dizziness", "standing", "orthostatic", "lightheaded"],
    urgent: false,
  },
  {
    id: "pain-radiating",
    label: "Pain radiating to the jaw, neck, back, or stomach",
    icon: "💢",
    keywords: ["radiating pain", "jaw", "neck", "back", "stomach", "referred pain"],
    urgent: true,
  },
  {
    id: "persistent-sadness",
    label: "Persistent sadness",
    icon: "😢",
    keywords: ["sadness", "sad", "depressed mood", "low mood"],
    urgent: false,
  },
  {
    id: "emptiness-hopelessness",
    label: "Feelings of emptiness or hopelessness",
    icon: "😔",
    keywords: ["emptiness", "hopelessness", "hopeless", "empty"],
    urgent: false,
  },
  {
    id: "constant-worrying",
    label: "Constant worrying",
    icon: "😟",
    keywords: ["worry", "worrying", "anxious thoughts"],
    urgent: false,
  },
  {
    id: "high-anxiety",
    label: "High anxiety",
    icon: "😰",
    keywords: ["anxiety", "anxious", "nervous"],
    urgent: false,
  },
  {
    id: "intense-irritability",
    label: "Intense irritability",
    icon: "😠",
    keywords: ["irritable", "irritability", "agitated"],
    urgent: false,
  },
  {
    id: "anger",
    label: "Anger",
    icon: "😤",
    keywords: ["anger", "angry", "rage"],
    urgent: false,
  },
  {
    id: "insomnia",
    label: "Insomnia",
    icon: "🌙",
    keywords: ["insomnia", "can't sleep", "sleepless"],
    urgent: false,
  },
  {
    id: "sleeping-excessively",
    label: "Sleeping excessively",
    icon: "😴",
    keywords: ["hypersomnia", "oversleeping", "sleeping too much"],
    urgent: false,
  },
  {
    id: "feeling-overwhelmed",
    label: "Feeling overwhelmed",
    icon: "😩",
    keywords: ["overwhelmed", "stressed", "too much"],
    urgent: false,
  },
  {
    id: "moderate-headache",
    label: "Moderate lingering headaches",
    icon: "🧠",
    keywords: ["headache", "lingering headache", "moderate headache"],
    urgent: false,
  },
  // —— Slightly unpleasant ——
  {
    id: "easily-winded",
    label: "Feeling easily winded",
    icon: "🫁",
    keywords: ["winded", "out of breath", "breathless"],
    urgent: false,
  },
  {
    id: "fatigue-routine-tasks",
    label: "Fatigue from routine tasks",
    icon: "😮‍💨",
    keywords: ["fatigue", "tired", "routine", "daily tasks"],
    urgent: false,
  },
  {
    id: "puffiness-mild",
    label: "Slight puffiness or tightness in fingers, ankles, or feet",
    icon: "🤏",
    keywords: ["puffiness", "tightness", "fingers", "ankles", "feet", "mild swelling"],
    urgent: false,
  },
  {
    id: "heart-flutters-occasional",
    label: "Occasional heart flutters",
    icon: "💓",
    keywords: ["heart flutters", "palpitations", "skipped beat"],
    urgent: false,
  },
  {
    id: "mild-stress",
    label: "Mild stress",
    icon: "😣",
    keywords: ["stress", "stressed", "mild stress"],
    urgent: false,
  },
  {
    id: "burned-out",
    label: 'Feeling "burned out"',
    icon: "🔥",
    keywords: ["burned out", "burnout", "exhausted"],
    urgent: false,
  },
  {
    id: "mild-mood-swings",
    label: "Mild mood swings",
    icon: "🎭",
    keywords: ["mood swings", "mood changes"],
    urgent: false,
  },
  {
    id: "low-motivation",
    label: "Low motivation",
    icon: "📉",
    keywords: ["motivation", "unmotivated", "low drive"],
    urgent: false,
  },
  {
    id: "mild-brain-fog",
    label: "Mild brain fog",
    icon: "🌫️",
    keywords: ["brain fog", "foggy", "cloudy thinking"],
    urgent: false,
  },
  {
    id: "forgetfulness",
    label: "Forgetfulness",
    icon: "🤔",
    keywords: ["forgetful", "memory", "forgetting"],
    urgent: false,
  },
  {
    id: "trouble-concentrating",
    label: "Trouble concentrating",
    icon: "🎯",
    keywords: ["concentration", "focus", "distracted"],
    urgent: false,
  },
  {
    id: "nausea-mild",
    label: "Mild nausea",
    icon: "🤢",
    keywords: ["nausea", "queasy", "mild nausea"],
    urgent: false,
  },
  {
    id: "decreased-appetite",
    label: "Decreased appetite",
    icon: "🍽️",
    keywords: ["appetite", "not hungry", "low appetite"],
    urgent: false,
  },
  {
    id: "fatigue-low-grade",
    label: "Low-grade fatigue",
    icon: "😑",
    keywords: ["fatigue", "tired", "low energy"],
    urgent: false,
  },
  {
    id: "sluggishness",
    label: "Sluggishness",
    icon: "🐢",
    keywords: ["sluggish", "slow", "lethargic"],
    urgent: false,
  },
  {
    id: "muscle-aches-mild",
    label: "Slight muscle aches",
    icon: "💪",
    keywords: ["muscle ache", "sore muscles", "aches"],
    urgent: false,
  },
  {
    id: "joint-stiffness",
    label: "Joint stiffness",
    icon: "🦴",
    keywords: ["stiff", "joints", "stiffness"],
    urgent: false,
  },
  {
    id: "tension-headache-mild",
    label: "Mild tension headache",
    icon: "🧠",
    keywords: ["tension headache", "headache", "mild headache"],
    urgent: false,
  },
  // —— Neutral ——
  {
    id: "normal-energy",
    label: "Normal energy levels",
    icon: "⚡",
    keywords: ["energy", "normal energy"],
    urgent: false,
  },
  {
    id: "steady-energy",
    label: "Steady energy",
    icon: "📊",
    keywords: ["steady energy", "consistent energy"],
    urgent: false,
  },
  {
    id: "no-physical-pain",
    label: "No physical pain",
    icon: "✅",
    keywords: ["no pain", "pain free"],
    urgent: false,
  },
  {
    id: "no-physical-discomfort",
    label: "No physical discomfort",
    icon: "✅",
    keywords: ["no discomfort", "comfortable"],
    urgent: false,
  },
  {
    id: "regular-sleep",
    label: "Regular sleep patterns",
    icon: "😴",
    keywords: ["sleep", "regular sleep", "sleep patterns"],
    urgent: false,
  },
  {
    id: "normal-appetite",
    label: "Normal appetite",
    icon: "🍽️",
    keywords: ["appetite", "normal appetite", "eating well"],
    urgent: false,
  },
  {
    id: "calm-mood",
    label: "Calm mood",
    icon: "😌",
    keywords: ["calm", "peaceful mood"],
    urgent: false,
  },
  {
    id: "emotionally-balanced",
    label: "Emotionally balanced",
    icon: "⚖️",
    keywords: ["balanced", "emotional balance", "stable mood"],
    urgent: false,
  },
  {
    id: "manageable-stress",
    label: "Manageable daily stress",
    icon: "🧘",
    keywords: ["stress", "manageable", "coping"],
    urgent: false,
  },
  {
    id: "clear-headedness",
    label: "Clear-headedness",
    icon: "💡",
    keywords: ["clear headed", "mental clarity", "alert"],
    urgent: false,
  },
  // —— Slightly pleasant ——
  {
    id: "relatively-energetic",
    label: "Feeling relatively energetic",
    icon: "⚡",
    keywords: ["energetic", "energy", "lively"],
    urgent: false,
  },
  {
    id: "feeling-refreshed",
    label: "Feeling refreshed",
    icon: "🌅",
    keywords: ["refreshed", "rested", "renewed"],
    urgent: false,
  },
  {
    id: "good-sleep-quality",
    label: "Good sleep quality",
    icon: "😴",
    keywords: ["sleep quality", "good sleep", "rested"],
    urgent: false,
  },
  {
    id: "minimal-discomfort",
    label: "Minimal physical discomfort",
    icon: "✨",
    keywords: ["minimal discomfort", "little discomfort"],
    urgent: false,
  },
  {
    id: "no-stiffness",
    label: "No physical stiffness",
    icon: "🙆",
    keywords: ["no stiffness", "flexible", "limber"],
    urgent: false,
  },
  {
    id: "content-mood",
    label: "Content mood",
    icon: "😊",
    keywords: ["content", "satisfied", "pleased"],
    urgent: false,
  },
  {
    id: "mild-optimism",
    label: "Mild optimism",
    icon: "🌤️",
    keywords: ["optimism", "optimistic", "hopeful"],
    urgent: false,
  },
  {
    id: "capable-daily-responsibilities",
    label: "Feeling capable of handling daily responsibilities",
    icon: "📋",
    keywords: ["capable", "responsibilities", "coping well"],
    urgent: false,
  },
  {
    id: "clear-thoughts",
    label: "Clear thoughts",
    icon: "💭",
    keywords: ["clear thoughts", "thinking clearly"],
    urgent: false,
  },
  {
    id: "steady-mood",
    label: "Steady mood",
    icon: "📈",
    keywords: ["steady mood", "stable mood", "even mood"],
    urgent: false,
  },
  // —— Pleasant ——
  {
    id: "high-energy",
    label: "High energy levels",
    icon: "⚡",
    keywords: ["high energy", "energetic", "vigorous"],
    urgent: false,
  },
  {
    id: "physically-comfortable",
    label: "Physically comfortable",
    icon: "🛋️",
    keywords: ["comfortable", "physical comfort"],
    urgent: false,
  },
  {
    id: "physically-thriving",
    label: "Physically thriving",
    icon: "🌟",
    keywords: ["thriving", "well", "healthy body"],
    urgent: false,
  },
  {
    id: "exercise-easily",
    label: "Able to exercise easily",
    icon: "🏃",
    keywords: ["exercise", "active", "workout"],
    urgent: false,
  },
  {
    id: "no-unusual-fatigue",
    label: "No unusual fatigue",
    icon: "✅",
    keywords: ["no fatigue", "not tired"],
    urgent: false,
  },
  {
    id: "no-sob-movement",
    label: "No shortness of breath during movement",
    icon: "🫁",
    keywords: ["no shortness of breath", "breathing well", "movement"],
    urgent: false,
  },
  {
    id: "happy",
    label: "Happy",
    icon: "😄",
    keywords: ["happy", "happiness", "joyful"],
    urgent: false,
  },
  {
    id: "motivated",
    label: "Motivated",
    icon: "🎯",
    keywords: ["motivated", "motivation", "driven"],
    urgent: false,
  },
  {
    id: "peaceful",
    label: "Peaceful",
    icon: "🕊️",
    keywords: ["peaceful", "peace", "serene"],
    urgent: false,
  },
  {
    id: "socially-connected",
    label: "Feeling socially connected",
    icon: "🤝",
    keywords: ["connected", "social", "community", "friends"],
    urgent: false,
  },
  {
    id: "stress-resilience-high",
    label: "High resilience to stress",
    icon: "🛡️",
    keywords: ["resilience", "stress resilience", "coping"],
    urgent: false,
  },
  // —— Very pleasant ——
  {
    id: "peak-vitality",
    label: "Peak physical vitality",
    icon: "💪",
    keywords: ["vitality", "peak", "vibrant"],
    urgent: false,
  },
  {
    id: "peak-strength",
    label: "Peak strength",
    icon: "🏋️",
    keywords: ["strength", "strong", "powerful"],
    urgent: false,
  },
  {
    id: "completely-rejuvenated",
    label: "Completely rejuvenated",
    icon: "🌺",
    keywords: ["rejuvenated", "renewed", "restored"],
    urgent: false,
  },
  {
    id: "exceptional-energy",
    label: "Exceptional energy",
    icon: "⚡",
    keywords: ["exceptional energy", "boundless energy"],
    urgent: false,
  },
  {
    id: "deep-joy",
    label: "Deep sense of joy",
    icon: "💖",
    keywords: ["joy", "joyful", "bliss"],
    urgent: false,
  },
  {
    id: "highly-inspired",
    label: "Highly inspired",
    icon: "✨",
    keywords: ["inspired", "inspiration", "creative"],
    urgent: false,
  },
  {
    id: "highly-productive",
    label: "Highly productive",
    icon: "📈",
    keywords: ["productive", "productivity", "accomplished"],
    urgent: false,
  },
  {
    id: "complete-mental-clarity",
    label: "Complete mental clarity",
    icon: "🧠",
    keywords: ["mental clarity", "clear mind", "sharp"],
    urgent: false,
  },
  {
    id: "excellent-emotional-wellbeing",
    label: "Excellent emotional well-being",
    icon: "🌈",
    keywords: ["emotional wellbeing", "well-being", "flourishing"],
    urgent: false,
  },
];

export const SYMPTOMS_CATALOG: SymptomDefinition[] = [
  ...LEGACY_URGENT,
  ...MOOD_TIER_SYMPTOMS,
];

export function getSymptomById(id: string): SymptomDefinition | undefined {
  return SYMPTOMS_CATALOG.find((s) => s.id === id);
}

const PILL_SHORT: Record<string, string> = {
  headache: "Severe headache",
  dizziness: "Dizziness / fainting",
  vision: "Vision changes",
  fever: "Fever",
  swelling: "Face/hand swelling",
  "harm-thoughts": "Harm thoughts",
  breathing: "Trouble breathing",
  "chest-pain": "Chest pain",
  nausea: "Severe nausea",
  "belly-pain": "Severe belly pain",
  "baby-movement": "Baby movement",
  "leg-pain": "Leg/arm pain",
  "bleeding-pregnancy": "Bleeding (pregnancy)",
  "bleeding-postpartum": "Bleeding (postpartum)",
  tiredness: "Overwhelming tiredness",
  "chest-pressure-squeezing": "Chest pressure",
  "racing-heart": "Racing heart",
  "sudden-shortness-breath": "Sudden SOB",
  "severe-panic": "Severe panic",
  "detachment-reality": "Detachment",
  "dizziness-sudden": "Sudden dizziness",
  fainting: "Fainting",
  "swelling-extreme-body": "Extreme swelling",
  "numbness-weakness-sudden": "Numbness / weakness",
  "chest-discomfort-mild": "Mild chest discomfort",
  "sob-light-activity": "SOB (light activity)",
  "swelling-ankles-feet": "Ankle/foot swelling",
  "dizziness-standing": "Dizziness standing",
  "pain-radiating": "Radiating pain",
  "persistent-sadness": "Persistent sadness",
  "emptiness-hopelessness": "Emptiness / hopelessness",
  "constant-worrying": "Constant worrying",
  "high-anxiety": "High anxiety",
  "intense-irritability": "Irritability",
  anger: "Anger",
  insomnia: "Insomnia",
  "sleeping-excessively": "Sleeping excessively",
  "feeling-overwhelmed": "Overwhelmed",
  "moderate-headache": "Moderate headache",
  "easily-winded": "Easily winded",
  "fatigue-routine-tasks": "Routine-task fatigue",
  "puffiness-mild": "Mild puffiness",
  "heart-flutters-occasional": "Heart flutters",
  "mild-stress": "Mild stress",
  "burned-out": "Burned out",
  "mild-mood-swings": "Mood swings",
  "low-motivation": "Low motivation",
  "mild-brain-fog": "Brain fog",
  forgetfulness: "Forgetfulness",
  "trouble-concentrating": "Trouble concentrating",
  "nausea-mild": "Mild nausea",
  "decreased-appetite": "Decreased appetite",
  "fatigue-low-grade": "Low-grade fatigue",
  sluggishness: "Sluggishness",
  "muscle-aches-mild": "Muscle aches",
  "joint-stiffness": "Joint stiffness",
  "tension-headache-mild": "Tension headache",
  "normal-energy": "Normal energy",
  "steady-energy": "Steady energy",
  "no-physical-pain": "No pain",
  "no-physical-discomfort": "No discomfort",
  "regular-sleep": "Regular sleep",
  "normal-appetite": "Normal appetite",
  "calm-mood": "Calm mood",
  "emotionally-balanced": "Emotionally balanced",
  "manageable-stress": "Manageable stress",
  "clear-headedness": "Clear-headed",
  "relatively-energetic": "Relatively energetic",
  "feeling-refreshed": "Refreshed",
  "good-sleep-quality": "Good sleep",
  "minimal-discomfort": "Minimal discomfort",
  "no-stiffness": "No stiffness",
  "content-mood": "Content",
  "mild-optimism": "Mild optimism",
  "capable-daily-responsibilities": "Capable / responsibilities",
  "clear-thoughts": "Clear thoughts",
  "steady-mood": "Steady mood",
  "high-energy": "High energy",
  "physically-comfortable": "Physically comfortable",
  "physically-thriving": "Physically thriving",
  "exercise-easily": "Exercise easily",
  "no-unusual-fatigue": "No unusual fatigue",
  "no-sob-movement": "No SOB on movement",
  happy: "Happy",
  motivated: "Motivated",
  peaceful: "Peaceful",
  "socially-connected": "Socially connected",
  "stress-resilience-high": "Stress resilient",
  "peak-vitality": "Peak vitality",
  "peak-strength": "Peak strength",
  "completely-rejuvenated": "Rejuvenated",
  "exceptional-energy": "Exceptional energy",
  "deep-joy": "Deep joy",
  "highly-inspired": "Highly inspired",
  "highly-productive": "Highly productive",
  "complete-mental-clarity": "Mental clarity",
  "excellent-emotional-wellbeing": "Emotional well-being",
};

export function getSymptomPillLabel(symptom: SymptomDefinition): string {
  return symptom.shortLabel ?? PILL_SHORT[symptom.id] ?? symptom.label;
}

export function searchSymptoms(query: string): SymptomDefinition[] {
  const q = query.trim().toLowerCase();
  if (!q) return SYMPTOMS_CATALOG;
  return SYMPTOMS_CATALOG.filter(
    (s) =>
      s.label.toLowerCase().includes(q) ||
      s.keywords.some((k) => k.includes(q) || q.includes(k)) ||
      (PILL_SHORT[s.id]?.toLowerCase().includes(q) ?? false),
  );
}
