import type { ChatMode } from "./types";

export interface IntentTestCase {
  message: string;
  expected: ChatMode;
  note?: string;
}

/** 100+ labeled examples for rule-based intent regression tests. */
export const INTENT_TEST_CASES: IntentTestCase[] = [
  // SAFETY_TRIAGE (28)
  { message: "I have chest pain", expected: "SAFETY_TRIAGE" },
  { message: "chest pain and shortness of breath", expected: "SAFETY_TRIAGE" },
  { message: "I can't breathe", expected: "SAFETY_TRIAGE" },
  { message: "trouble breathing while pregnant", expected: "SAFETY_TRIAGE" },
  { message: "I think I'm having a heart attack", expected: "SAFETY_TRIAGE" },
  { message: "stroke symptoms facial drooping", expected: "SAFETY_TRIAGE" },
  { message: "I fainted twice today", expected: "SAFETY_TRIAGE" },
  { message: "passed out after standing up", expected: "SAFETY_TRIAGE" },
  { message: "severe headache and vision changes", expected: "SAFETY_TRIAGE" },
  { message: "sudden blurry vision pregnant", expected: "SAFETY_TRIAGE" },
  { message: "extreme swelling in my legs and face", expected: "SAFETY_TRIAGE" },
  { message: "severe belly pain 32 weeks pregnant", expected: "SAFETY_TRIAGE" },
  { message: "heavy bleeding postpartum", expected: "SAFETY_TRIAGE" },
  { message: "my bp is 190/120", expected: "SAFETY_TRIAGE" },
  { message: "blood pressure reading 185/115", expected: "SAFETY_TRIAGE" },
  { message: "pregnant and can't catch my breath", expected: "SAFETY_TRIAGE" },
  { message: "postpartum chest pain", expected: "SAFETY_TRIAGE" },
  { message: "I want to die", expected: "SAFETY_TRIAGE" },
  { message: "I want to kill myself", expected: "SAFETY_TRIAGE" },
  { message: "I'm suicidal", expected: "SAFETY_TRIAGE" },
  { message: "dead", expected: "SAFETY_TRIAGE" },
  { message: "blue lips and dizziness", expected: "SAFETY_TRIAGE" },
  { message: "heart pain radiating to my arm", expected: "SAFETY_TRIAGE" },
  { message: "severe abdominal pain pregnant", expected: "SAFETY_TRIAGE" },
  { message: "my chest hurts so bad", expected: "SAFETY_TRIAGE" },
  { message: "slurred speech sudden weakness", expected: "SAFETY_TRIAGE" },
  { message: "pregnancy bleeding and pain", expected: "SAFETY_TRIAGE" },
  { message: "I have stomach pain and feel faint", expected: "SAFETY_TRIAGE" },

  // NAVIGATION (14)
  { message: "show my heart trends", expected: "NAVIGATION" },
  { message: "open heart dashboard", expected: "NAVIGATION" },
  { message: "go to pregnancy insights", expected: "NAVIGATION" },
  { message: "take me to emergency resources", expected: "NAVIGATION" },
  { message: "open symptom tracker", expected: "NAVIGATION" },
  { message: "show wearables", expected: "NAVIGATION" },
  { message: "open settings", expected: "NAVIGATION" },
  { message: "view my reports", expected: "NAVIGATION" },
  { message: "go to education hub", expected: "NAVIGATION" },
  { message: "open risk scanner", expected: "NAVIGATION" },
  { message: "show postpartum recovery", expected: "NAVIGATION" },
  { message: "navigate to home", expected: "NAVIGATION" },
  { message: "see my chat history", expected: "NAVIGATION" },
  { message: "display my heart dashboard", expected: "NAVIGATION" },

  // APP_ACTION (12)
  { message: "log my symptoms for today", expected: "APP_ACTION" },
  { message: "track my blood pressure", expected: "APP_ACTION" },
  { message: "record my mood", expected: "APP_ACTION" },
  { message: "add a symptom entry", expected: "APP_ACTION" },
  { message: "sync my apple watch", expected: "APP_ACTION" },
  { message: "connect my fitbit", expected: "APP_ACTION" },
  { message: "log my heart rate", expected: "APP_ACTION" },
  { message: "save my bpm reading", expected: "APP_ACTION" },
  { message: "start tracking my period", expected: "APP_ACTION" },
  { message: "enter my medication", expected: "APP_ACTION" },
  { message: "set a reminder for bp", expected: "APP_ACTION" },
  { message: "enable notifications", expected: "APP_ACTION" },

  // VITALS_CHECK (12)
  { message: "is 120/80 a normal blood pressure", expected: "VITALS_CHECK" },
  { message: "my bp is 130/85 is that ok", expected: "VITALS_CHECK" },
  { message: "what is a healthy resting heart rate", expected: "BASIC_EDUCATION" },
  { message: "my heart rate is 72 bpm", expected: "VITALS_CHECK" },
  { message: "is my blood pressure high at 140/90", expected: "VITALS_CHECK" },
  { message: "blood pressure reading 118/76 today", expected: "VITALS_CHECK" },
  { message: "heart rate trend this week", expected: "VITALS_CHECK" },
  { message: "is 98 bpm too high", expected: "VITALS_CHECK" },
  { message: "what is normal bpm for women", expected: "BASIC_EDUCATION" },
  { message: "my pulse is 88 is that okay", expected: "VITALS_CHECK" },
  { message: "bp average over time", expected: "VITALS_CHECK" },
  { message: "is low blood pressure 90/60 bad", expected: "VITALS_CHECK" },

  // MOOD_SUPPORT (10)
  { message: "I'm sad today", expected: "MOOD_SUPPORT" },
  { message: "feeling anxious about pregnancy", expected: "MOOD_SUPPORT" },
  { message: "I'm stressed and overwhelmed", expected: "MOOD_SUPPORT" },
  { message: "having a rough day", expected: "MOOD_SUPPORT" },
  { message: "I feel down postpartum", expected: "MOOD_SUPPORT" },
  { message: "feeling lonely", expected: "MOOD_SUPPORT" },
  { message: "I'm worried all the time", expected: "MOOD_SUPPORT" },
  { message: "not okay mentally", expected: "MOOD_SUPPORT" },
  { message: "I am feeling off", expected: "MOOD_SUPPORT" },
  { message: "bad day emotionally", expected: "MOOD_SUPPORT" },

  // DOCTOR_PREP (10)
  { message: "questions for my doctor appointment", expected: "DOCTOR_PREP" },
  { message: "what should I ask my OB", expected: "DOCTOR_PREP" },
  { message: "prepare for my prenatal visit", expected: "DOCTOR_PREP" },
  { message: "doctor appointment tomorrow what to bring", expected: "DOCTOR_PREP" },
  { message: "what to tell my doctor about chest tightness", expected: "DOCTOR_PREP" },
  { message: "visit summary for my provider", expected: "DOCTOR_PREP" },
  { message: "questions for my midwife", expected: "DOCTOR_PREP" },
  { message: "help me prepare for cardiology visit", expected: "DOCTOR_PREP" },
  { message: "help me write a doctor visit summary", expected: "DOCTOR_PREP" },
  { message: "what to tell my doctor about postpartum symptoms", expected: "DOCTOR_PREP" },

  // BASIC_EDUCATION (14)
  { message: "what is blood pressure", expected: "BASIC_EDUCATION" },
  { message: "what is PCOS", expected: "BASIC_EDUCATION" },
  { message: "what is cholesterol", expected: "BASIC_EDUCATION" },
  { message: "what is preeclampsia", expected: "BASIC_EDUCATION" },
  { message: "define hypertension", expected: "BASIC_EDUCATION" },
  { message: "explain heart failure simply", expected: "BASIC_EDUCATION" },
  { message: "what are triglycerides", expected: "BASIC_EDUCATION" },
  { message: "tell me about gestational diabetes", expected: "BASIC_EDUCATION" },
  { message: "what is a normal heart rate", expected: "BASIC_EDUCATION" },
  { message: "how does the heart pump blood", expected: "BASIC_EDUCATION" },
  { message: "what is peripartum cardiomyopathy", expected: "BASIC_EDUCATION" },
  { message: "what is LDL", expected: "BASIC_EDUCATION" },
  { message: "explain postpartum cardiomyopathy in simple terms", expected: "BASIC_EDUCATION" },
  { message: "what is atherosclerosis", expected: "BASIC_EDUCATION" },

  // RAG_MEDICAL (22)
  { message: "signs of preeclampsia in pregnancy", expected: "RAG_MEDICAL" },
  { message: "symptoms of postpartum cardiomyopathy", expected: "RAG_MEDICAL" },
  { message: "do I have PCOS", expected: "RAG_MEDICAL" },
  { message: "could I have preeclampsia", expected: "RAG_MEDICAL" },
  { message: "risk factors for heart disease in women", expected: "RAG_MEDICAL" },
  { message: "how to prevent cardiovascular disease during pregnancy", expected: "RAG_MEDICAL" },
  { message: "maternal heart disease complications", expected: "RAG_MEDICAL" },
  { message: "postpartum cardiovascular risks", expected: "RAG_MEDICAL" },
  { message: "screening for gestational hypertension", expected: "RAG_MEDICAL" },
  { message: "labs for cholesterol in women", expected: "RAG_MEDICAL" },
  { message: "treatment for high blood pressure in pregnancy", expected: "RAG_MEDICAL" },
  { message: "why do women have different heart attack symptoms", expected: "RAG_MEDICAL" },
  { message: "what causes peripartum heart failure", expected: "RAG_MEDICAL" },
  { message: "am I at risk for preeclampsia", expected: "RAG_MEDICAL" },
  { message: "polycystic ovary syndrome and heart risk", expected: "RAG_MEDICAL" },
  { message: "pregnancy heart health guidelines", expected: "RAG_MEDICAL" },
  { message: "complications of preeclampsia", expected: "RAG_MEDICAL" },
  { message: "women's heart attack warning signs", expected: "RAG_MEDICAL" },
  { message: "postpartum heart symptoms to watch for", expected: "RAG_MEDICAL" },
  { message: "gestational hypertension management", expected: "RAG_MEDICAL" },
  { message: "cardiovascular screening during prenatal care", expected: "RAG_MEDICAL" },
  { message: "medication safety in pregnancy hypertension", expected: "RAG_MEDICAL" },
  {
    message: "what can I do to prevent a heart attack - im not having one",
    expected: "RAG_MEDICAL",
    note: "prevention not emergency",
  },
  {
    message: "will I get a heartattack",
    expected: "RAG_MEDICAL",
    note: "hypothetical not emergency",
  },

  // MOOD_SUPPORT extras
  { message: "my boyfriend broke up with me", expected: "MOOD_SUPPORT" },

  // OUT_OF_SCOPE (12)
  { message: "what's the weather today", expected: "OUT_OF_SCOPE" },
  { message: "write me a python script", expected: "OUT_OF_SCOPE" },
  { message: "bitcoin price", expected: "OUT_OF_SCOPE" },
  { message: "tell me a joke", expected: "OUT_OF_SCOPE" },
  { message: "recipe for pasta", expected: "OUT_OF_SCOPE" },
  { message: "who won the super bowl", expected: "OUT_OF_SCOPE" },
  { message: "help with homework", expected: "OUT_OF_SCOPE" },
  { message: "stock market tips", expected: "OUT_OF_SCOPE" },
  { message: "hello", expected: "OUT_OF_SCOPE", note: "greeting" },
  { message: "thanks", expected: "OUT_OF_SCOPE", note: "greeting" },
  { message: "book a flight to Paris", expected: "OUT_OF_SCOPE" },
  { message: "best movies 2024", expected: "OUT_OF_SCOPE" },
];
